<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mia3_location"
 *
 * Auto generated by Extension Builder 2013-09-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MIA3 Locations',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Marc Neuhaus',
	'author_email' => 'marc@mia3.com',
	'author_company' => 'MIA3',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'static_info_tables' => '*'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
