<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "famelo_location"
 *
 * Auto generated by Extension Builder 2013-09-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Famelo Locations',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Marc Neuhaus',
	'author_email' => 'apocalip@gmail.com',
	'author_company' => 'Famelo OHG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>